### ISSUE TITLE
mask test failing on nightly build

### ISSUE THREAD

**Issue by tylerjthomas9** [chengchingwen/NeuralAttentionlib.jl#11]
One of the tests fails for me when running them on the nightly build, but not 1.6.2. Here is the test:
https://github.com/chengchingwen/NeuralAttentionlib.jl/blob/e8f5adbb52902d148fb87f1e5c5f8a67727ab3cb/test/mask.jl#L214

Changing the tolerance to 2e-2 causes the test to pass, but I am not sure if there is an underlying issue causing this divergence from 1.6. Here is the test output:

`
test_rrule: apply_broadcast_mask on typeof(+),NeuralAttentionlib.CombinedMask{typeof(|), Tuple{LocalMask, NeuralAttentionlib.CombinedMask{typeof(&), Tuple{CausalMask, NeuralAttentionlib.FlipMask{BandPartMask}}}, BiLengthMask{1, Vector{Int32}, False}}},Array{Float64, 3},Float64: Test Failed at /home/tyler/.julia/packages/ChainRulesTestUtils/Rzheq/src/check_result.jl:24
  Expression: isapprox(actual, expected; kwargs...)
   Evaluated: isapprox([2.72 6.99 … -4.84 -1.89; 2.94 -1.41 … -6.66 3.7; … ; -7.28 -7.71 … -0.43 6.4; -3.53 2.58 … -3.32 -1.93;;; 8.53 4.79 … -2.35 7.41; 4.82 -8.45 … 7.61 8.43; … ; -1.21 -3.46 … -8.96 -3.36; 8.82 -1.97 … 5.2 -4.43], [2.7211662132971557 6.9912583779764965 … -4.838677717275233 -1.8888861389749363; 2.9413156646614165 -1.4088806879791433 … -6.65927320175628 3.7009924015743145; … ; -7.278864675679232 -7.708864675678956 … -0.4288695588627337 6.401135324320659; -3.528864675679001 2.5811353243210413 … -3.3188646756789826 -1.9287901240841108;;; 8.53165855666922 4.791159792790158 … -2.3488766800427876 7.410849092549938; 4.8211900614037475 -8.44890784030623 … 7.6108889142861536 8.431178386783428; … ; -1.208864675679073 -3.458864675678981 … -8.958910445508586 -3.3588646756790794; 8.821135324321409 -1.968864675679025 … 5.201135324320997 -4.428914983827672]; rtol = 1.0e-9, atol = 1.0e-9)
Stacktrace:
 [1] test_approx(actual::Union{Number, AbstractArray{<:Number}}, expected::Union{Number, AbstractArray{<:Number}}, msg::Any; kwargs::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}})
   @ ChainRulesTestUtils ~/.julia/packages/ChainRulesTestUtils/Rzheq/src/check_result.jl:24
 [2] macro expansion
   @ ~/.julia/packages/ChainRulesTestUtils/Rzheq/src/testers.jl:238 [inlined]
 [3] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
 [4] test_rrule(::RuleConfig, ::Any, ::Any, ::Vararg{Any}; output_tangent::Any, check_thunked_output_tangent::Any, fdm::Any, rrule_f::Any, check_inferred::Bool, fkwargs::NamedTuple, rtol::Real, atol::Real, kwargs::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}})
   @ ChainRulesTestUtils ~/.julia/packages/ChainRulesTestUtils/Rzheq/src/testers.jl:194
`

**Comment by chengchingwen** [comment]
Maybe some precision of underlying operation change, I guess. But it probably won't affect using this package?

**Comment by chengchingwen** [comment]
@tylerjthomas9 If you are using this package, let me know what do you feel about the experience. We can see if anything need to be improved.

**Comment by tylerjthomas9** [comment]
Slowly learning Flux.jl as I transition over from PyTorch in my free time. Looking to contribute to Transformers.jl and this library as I get up to a working level. Current plan is to implement a basic tabular transformer network this weekend using NeuralAttentionlib.jl, so I'll let you know what I think. Great work! Using a lot of your Flux.jl stuff as a learning resource

**Comment by tylerjthomas9** [comment]
Finally got time to get familiar enough with Flux to implement a transformer layer. Using the atten(mha, x) method shown in  test/mha.jl made everything a lot easier. How do you see this library evolving? I imagine that support for things like linear attention would be useful for porting models from HF such as longformer at some point.

**Comment by chengchingwen** [comment]
Yes, that's what I'm thinking when writing this library. Ideally I'd like to support many different attention operations with each one being composed by some small reusable functions, so people can implement some custom attention without having to write redundant or duplicate code
